target 'Peek' do
pod 'MJRefresh'
pod 'SVProgressHUD'
pod 'SDWebImage'
pod 'BmobSDK'
pod 'MJExtension'
pod 'JVFloatLabeledTextField'
pod 'FlatUIKit'
pod 'UMengUShare/UI'
pod 'UMengUShare/Social/ReducedWeChat'
pod 'SMSSDK'
pod 'IQKeyboardManager'
pod 'RongCloudIM/IMLib'
pod 'RongCloudIM/IMKit'
end
